In [1]:

import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'd:\\Programs\\ML\\venv\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [4]:
string = tf.Variable("mango is noice", tf.string)
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'mango is noice'>


RANKS (these terms simply mean the number of dimensions involved in the tensor)
eg:- 2D array has rank 2 1D array has rank 1 and no array has rank 0.
In the output the numpy dipicts the rank of the variable

In [7]:
rank0_var = tf.Variable("mango",tf.string)
rank1_var = tf.Variable(["mango","is","good"], tf.string)
rank2_var = tf.Variable([['mango','is'],['not','good']], tf.string)
tf.rank(rank1_var)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

SHAPE (The shape of a tensor is simply the number of elements that exist in each dimension)

In [9]:
rank2_var.shape

TensorShape([2, 2])

RESHAPING (The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.)

In [10]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]
# The numer of elements in the reshaped tensor MUST match the number in the original
# tf.ones([1,2,3]) 1 = number of matrix 2 = rows 3 = columns

In [11]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [16]:
tensor1 = tf.ones([2,2,5])
print(tensor1)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 2, 5), dtype=float32)


In [1]:
x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2

NameError: name 'tf' is not defined

In [ ]:
tf.get_default_session().run(f)

In [ ]:
init= tf.global_variable_initializer()
with tf.Session() as sess:
    init.run()
    result = f.eval()
    